// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scan.proto

/*
Package scan is a generated protocol buffer package.

It is generated from these files:
	scan.proto

It has these top-level messages:
	Options
	Id
	Destination
	Progress
	Job
	Jobs
*/
package scan

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State__         State = 0
	State_STARTED   State = 1
	State_COMPLETED State = 2
	State_CANCELLED State = 3
	State_FAILED    State = 4
	State_TIMED_OUT State = 5
)

var State_name = map[int32]string{
	0: "_",
	1: "STARTED",
	2: "COMPLETED",
	3: "CANCELLED",
	4: "FAILED",
	5: "TIMED_OUT",
}
var State_value = map[string]int32{
	"_":         0,
	"STARTED":   1,
	"COMPLETED": 2,
	"CANCELLED": 3,
	"FAILED":    4,
	"TIMED_OUT": 5,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Options struct {
	Number int64                              `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Delay  int64                              `protobuf:"varint,2,opt,name=delay" json:"delay,omitempty"`
	Extra  map[string]*google_protobuf1.Value `protobuf:"bytes,3,rep,name=extra" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Options) Reset()                    { *m = Options{} }
func (m *Options) String() string            { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()               {}
func (*Options) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Options) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Options) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *Options) GetExtra() map[string]*google_protobuf1.Value {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Id struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Destination struct {
	Id    string                             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Extra map[string]*google_protobuf1.Value `protobuf:"bytes,2,rep,name=extra" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Destination) Reset()                    { *m = Destination{} }
func (m *Destination) String() string            { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()               {}
func (*Destination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Destination) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Destination) GetExtra() map[string]*google_protobuf1.Value {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Progress struct {
	Started   int64 `protobuf:"varint,1,opt,name=started" json:"started,omitempty"`
	Completed int64 `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
	Duration  int64 `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
}

func (m *Progress) Reset()                    { *m = Progress{} }
func (m *Progress) String() string            { return proto.CompactTextString(m) }
func (*Progress) ProtoMessage()               {}
func (*Progress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Progress) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Progress) GetCompleted() int64 {
	if m != nil {
		return m.Completed
	}
	return 0
}

func (m *Progress) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type Job struct {
	Id           string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Options      *Options       `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	State        State          `protobuf:"varint,3,opt,name=state,enum=scan.State" json:"state,omitempty"`
	Destinations []*Destination `protobuf:"bytes,4,rep,name=destinations" json:"destinations,omitempty"`
	Progress     *Progress      `protobuf:"bytes,5,opt,name=progress" json:"progress,omitempty"`
	Message      string         `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Job) GetState() State {
	if m != nil {
		return m.State
	}
	return State__
}

func (m *Job) GetDestinations() []*Destination {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *Job) GetProgress() *Progress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *Job) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Jobs struct {
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *Jobs) Reset()                    { *m = Jobs{} }
func (m *Jobs) String() string            { return proto.CompactTextString(m) }
func (*Jobs) ProtoMessage()               {}
func (*Jobs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Jobs) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Options)(nil), "scan.Options")
	proto.RegisterType((*Id)(nil), "scan.Id")
	proto.RegisterType((*Destination)(nil), "scan.Destination")
	proto.RegisterType((*Progress)(nil), "scan.Progress")
	proto.RegisterType((*Job)(nil), "scan.Job")
	proto.RegisterType((*Jobs)(nil), "scan.Jobs")
	proto.RegisterEnum("scan.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scan service

type ScanClient interface {
	Start(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Id, error)
	Status(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Jobs, error)
	Cancel(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Job, error)
}

type scanClient struct {
	cc *grpc.ClientConn
}

func NewScanClient(cc *grpc.ClientConn) ScanClient {
	return &scanClient{cc}
}

func (c *scanClient) Start(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/scan.Scan/Start", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) Status(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Jobs, error) {
	out := new(Jobs)
	err := grpc.Invoke(ctx, "/scan.Scan/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) Cancel(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := grpc.Invoke(ctx, "/scan.Scan/Cancel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scan service

type ScanServer interface {
	Start(context.Context, *Options) (*Id, error)
	Status(context.Context, *Id) (*Jobs, error)
	Cancel(context.Context, *Id) (*Job, error)
}

func RegisterScanServer(s *grpc.Server, srv ScanServer) {
	s.RegisterService(&_Scan_serviceDesc, srv)
}

func _Scan_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Options)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scan.Scan/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Start(ctx, req.(*Options))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scan.Scan/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Status(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scan.Scan/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Cancel(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scan.Scan",
	HandlerType: (*ScanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Scan_Start_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Scan_Status_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Scan_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scan.proto",
}

func init() { proto.RegisterFile("scan.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x76, 0x7f, 0x93, 0x9c, 0xb4, 0x65, 0x3d, 0x94, 0xb2, 0x84, 0x0a, 0x75, 0x41, 0x2c, 0x41,
	0x36, 0xb8, 0x22, 0x48, 0xef, 0x4a, 0xb3, 0x42, 0x4a, 0x6b, 0xcb, 0x26, 0x7a, 0x69, 0x99, 0xcd,
	0x8e, 0x61, 0x35, 0xdd, 0x09, 0x3b, 0xb3, 0x62, 0x10, 0x6f, 0x7c, 0x05, 0x9f, 0x40, 0x7c, 0x0a,
	0x9f, 0xc3, 0x7b, 0xaf, 0x7c, 0x10, 0x99, 0x99, 0xdd, 0xfc, 0xd8, 0x7b, 0xef, 0xe6, 0x3b, 0xdf,
	0xf9, 0xce, 0x7c, 0xe7, 0x9b, 0x01, 0xe0, 0x53, 0x52, 0x84, 0x8b, 0x92, 0x09, 0x86, 0xb6, 0x3c,
	0xf7, 0x0e, 0x67, 0x8c, 0xcd, 0xe6, 0x74, 0x40, 0x16, 0xf9, 0x80, 0x14, 0x05, 0x13, 0x44, 0xe4,
	0xac, 0xe0, 0xba, 0x67, 0xc5, 0x2a, 0x94, 0x56, 0xef, 0x06, 0x5c, 0x94, 0xd5, 0x54, 0x68, 0x36,
	0xf8, 0x69, 0x40, 0xeb, 0x6a, 0xa1, 0xfa, 0xf1, 0x00, 0xdc, 0xa2, 0xba, 0x4d, 0x69, 0xe9, 0x1b,
	0x47, 0xc6, 0xb1, 0x95, 0xd4, 0x08, 0xf7, 0xc1, 0xc9, 0xe8, 0x9c, 0x2c, 0x7d, 0x53, 0x95, 0x35,
	0xc0, 0x10, 0x1c, 0xfa, 0x49, 0x94, 0xc4, 0xb7, 0x8e, 0xac, 0xe3, 0x6e, 0xe4, 0x87, 0xca, 0x57,
	0x3d, 0x2b, 0x8c, 0x25, 0x15, 0x17, 0xa2, 0x5c, 0x26, 0xba, 0xad, 0x77, 0x0d, 0xb0, 0x2e, 0xa2,
	0x07, 0xd6, 0x07, 0xba, 0x54, 0x17, 0x75, 0x12, 0x79, 0xc4, 0x27, 0xe0, 0x7c, 0x24, 0xf3, 0x8a,
	0xaa, 0x5b, 0xba, 0xd1, 0x41, 0xa8, 0x7d, 0x87, 0x8d, 0xef, 0xf0, 0x8d, 0x64, 0x13, 0xdd, 0x74,
	0x62, 0xbe, 0x30, 0x82, 0x7d, 0x30, 0x47, 0x19, 0xee, 0x81, 0x99, 0x67, 0xf5, 0x20, 0x33, 0xcf,
	0x82, 0x1f, 0x06, 0x74, 0x87, 0x94, 0x8b, 0xbc, 0x50, 0x31, 0xfc, 0xcb, 0x63, 0xd4, 0xf8, 0x36,
	0x95, 0xef, 0x43, 0xed, 0x7b, 0x43, 0xf1, 0x5f, 0xbc, 0xbf, 0x85, 0xf6, 0x75, 0xc9, 0x66, 0x25,
	0xe5, 0x1c, 0x7d, 0x68, 0x71, 0x41, 0x4a, 0x41, 0xb3, 0x3a, 0xf8, 0x06, 0xe2, 0x21, 0x74, 0xa6,
	0xec, 0x76, 0x31, 0xa7, 0x92, 0xd3, 0xe9, 0xaf, 0x0b, 0xd8, 0x83, 0x76, 0x56, 0x95, 0xca, 0xb3,
	0x6f, 0x29, 0x72, 0x85, 0x83, 0xdf, 0x06, 0x58, 0xe7, 0x2c, 0xbd, 0xb3, 0xfd, 0x63, 0x68, 0x31,
	0xfd, 0x44, 0xb5, 0xd7, 0xdd, 0xad, 0x77, 0x4b, 0x1a, 0x16, 0x1f, 0x82, 0xc3, 0x05, 0x11, 0x54,
	0x4d, 0xde, 0x8b, 0xba, 0xba, 0x6d, 0x2c, 0x4b, 0x89, 0x66, 0xf0, 0x39, 0xec, 0x64, 0xeb, 0xd8,
	0xb8, 0x6f, 0xab, 0x40, 0xef, 0xdf, 0x09, 0x34, 0xd9, 0x6a, 0xc3, 0x3e, 0xb4, 0x17, 0xf5, 0xea,
	0xbe, 0xa3, 0x3c, 0xec, 0x69, 0x49, 0x13, 0x48, 0xb2, 0xe2, 0x65, 0x34, 0xb7, 0x94, 0x73, 0x32,
	0xa3, 0xbe, 0xab, 0x76, 0x68, 0x60, 0xf0, 0x08, 0xec, 0x73, 0x96, 0x72, 0x7c, 0x00, 0xf6, 0x7b,
	0x96, 0x72, 0xdf, 0x50, 0x97, 0x77, 0xf4, 0xa4, 0x73, 0x96, 0x26, 0xaa, 0xdc, 0x9f, 0x80, 0xa3,
	0x3c, 0xa3, 0x03, 0xc6, 0x8d, 0x77, 0x0f, 0xbb, 0xd0, 0x1a, 0x4f, 0x4e, 0x93, 0x49, 0x3c, 0xf4,
	0x0c, 0xdc, 0x85, 0xce, 0xd9, 0xd5, 0xe5, 0xf5, 0x45, 0x2c, 0xa1, 0xa9, 0xe0, 0xe9, 0xab, 0xb3,
	0xf8, 0xe2, 0x22, 0x1e, 0x7a, 0x16, 0x02, 0xb8, 0x2f, 0x4f, 0x47, 0xf2, 0x6c, 0x4b, 0x6a, 0x32,
	0xba, 0x8c, 0x87, 0x37, 0x57, 0xaf, 0x27, 0x9e, 0x13, 0x7d, 0x37, 0xc0, 0x1e, 0x4f, 0x49, 0x21,
	0x3f, 0xd3, 0x58, 0xbe, 0x15, 0x6e, 0xc7, 0xd8, 0x6b, 0x6b, 0x38, 0xca, 0x02, 0xef, 0xeb, 0xaf,
	0x3f, 0xdf, 0x4c, 0x08, 0x9c, 0x81, 0xac, 0x9c, 0x18, 0x7d, 0x8c, 0xc0, 0x95, 0x96, 0x2a, 0x8e,
	0xab, 0xae, 0x1e, 0xac, 0x7c, 0xf3, 0x00, 0x95, 0x62, 0x07, 0x41, 0x29, 0x06, 0x9f, 0xf3, 0xec,
	0x0b, 0x3e, 0x05, 0xf7, 0x8c, 0x14, 0x53, 0x3a, 0xdf, 0xd0, 0xac, 0x77, 0x6d, 0x24, 0xfd, 0x0d,
	0x49, 0xea, 0xaa, 0xcf, 0xf7, 0xec, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x27, 0xea, 0x91,
	0x30, 0x04, 0x00, 0x00,
}
