/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('./google/api/annotations_pb.js');
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.exportSymbol('proto.adapter.Destination', null, global);
goog.exportSymbol('proto.adapter.Id', null, global);
goog.exportSymbol('proto.adapter.Job', null, global);
goog.exportSymbol('proto.adapter.Jobs', null, global);
goog.exportSymbol('proto.adapter.Progress', null, global);
goog.exportSymbol('proto.adapter.ScanKey', null, global);
goog.exportSymbol('proto.adapter.ScanOptions', null, global);
goog.exportSymbol('proto.adapter.State', null, global);
goog.exportSymbol('proto.adapter.UpdateKey', null, global);
goog.exportSymbol('proto.adapter.UpdateOptions', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.ScanKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adapter.ScanKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.ScanKey.displayName = 'proto.adapter.ScanKey';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.ScanKey.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.ScanKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.ScanKey} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.ScanKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    adapterApiKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    options: (f = msg.getOptions()) && proto.adapter.ScanOptions.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.ScanKey}
 */
proto.adapter.ScanKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.ScanKey;
  return proto.adapter.ScanKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.ScanKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.ScanKey}
 */
proto.adapter.ScanKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdapterApiKey(value);
      break;
    case 2:
      var value = new proto.adapter.ScanOptions;
      reader.readMessage(value,proto.adapter.ScanOptions.deserializeBinaryFromReader);
      msg.setOptions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.ScanKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.ScanKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.ScanKey} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.ScanKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAdapterApiKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOptions();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.adapter.ScanOptions.serializeBinaryToWriter
    );
  }
};


/**
 * optional string adapter_api_key = 1;
 * @return {string}
 */
proto.adapter.ScanKey.prototype.getAdapterApiKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.adapter.ScanKey.prototype.setAdapterApiKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional ScanOptions options = 2;
 * @return {?proto.adapter.ScanOptions}
 */
proto.adapter.ScanKey.prototype.getOptions = function() {
  return /** @type{?proto.adapter.ScanOptions} */ (
    jspb.Message.getWrapperField(this, proto.adapter.ScanOptions, 2));
};


/** @param {?proto.adapter.ScanOptions|undefined} value */
proto.adapter.ScanKey.prototype.setOptions = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.adapter.ScanKey.prototype.clearOptions = function() {
  this.setOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.adapter.ScanKey.prototype.hasOptions = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.ScanOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adapter.ScanOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.ScanOptions.displayName = 'proto.adapter.ScanOptions';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.ScanOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.ScanOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.ScanOptions} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.ScanOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    number: jspb.Message.getFieldWithDefault(msg, 2, 0),
    delay: jspb.Message.getFieldWithDefault(msg, 3, 0),
    extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.ScanOptions}
 */
proto.adapter.ScanOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.ScanOptions;
  return proto.adapter.ScanOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.ScanOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.ScanOptions}
 */
proto.adapter.ScanOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMode(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumber(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDelay(value);
      break;
    case 4:
      var value = msg.getExtraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.ScanOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.ScanOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.ScanOptions} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.ScanOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNumber();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getDelay();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getExtraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
};


/**
 * optional string mode = 1;
 * @return {string}
 */
proto.adapter.ScanOptions.prototype.getMode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.adapter.ScanOptions.prototype.setMode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int64 number = 2;
 * @return {number}
 */
proto.adapter.ScanOptions.prototype.getNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.adapter.ScanOptions.prototype.setNumber = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int64 delay = 3;
 * @return {number}
 */
proto.adapter.ScanOptions.prototype.getDelay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.adapter.ScanOptions.prototype.setDelay = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * map<string, google.protobuf.Value> extra = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.adapter.ScanOptions.prototype.getExtraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


proto.adapter.ScanOptions.prototype.clearExtraMap = function() {
  this.getExtraMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.UpdateKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adapter.UpdateKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.UpdateKey.displayName = 'proto.adapter.UpdateKey';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.UpdateKey.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.UpdateKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.UpdateKey} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.UpdateKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    adapterApiKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    options: (f = msg.getOptions()) && proto.adapter.UpdateOptions.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.UpdateKey}
 */
proto.adapter.UpdateKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.UpdateKey;
  return proto.adapter.UpdateKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.UpdateKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.UpdateKey}
 */
proto.adapter.UpdateKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdapterApiKey(value);
      break;
    case 2:
      var value = new proto.adapter.UpdateOptions;
      reader.readMessage(value,proto.adapter.UpdateOptions.deserializeBinaryFromReader);
      msg.setOptions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.UpdateKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.UpdateKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.UpdateKey} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.UpdateKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAdapterApiKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOptions();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.adapter.UpdateOptions.serializeBinaryToWriter
    );
  }
};


/**
 * optional string adapter_api_key = 1;
 * @return {string}
 */
proto.adapter.UpdateKey.prototype.getAdapterApiKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.adapter.UpdateKey.prototype.setAdapterApiKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional UpdateOptions options = 2;
 * @return {?proto.adapter.UpdateOptions}
 */
proto.adapter.UpdateKey.prototype.getOptions = function() {
  return /** @type{?proto.adapter.UpdateOptions} */ (
    jspb.Message.getWrapperField(this, proto.adapter.UpdateOptions, 2));
};


/** @param {?proto.adapter.UpdateOptions|undefined} value */
proto.adapter.UpdateKey.prototype.setOptions = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.adapter.UpdateKey.prototype.clearOptions = function() {
  this.setOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.adapter.UpdateKey.prototype.hasOptions = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.UpdateOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.adapter.UpdateOptions.repeatedFields_, null);
};
goog.inherits(proto.adapter.UpdateOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.UpdateOptions.displayName = 'proto.adapter.UpdateOptions';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.adapter.UpdateOptions.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.UpdateOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.UpdateOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.UpdateOptions} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.UpdateOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    mode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    image: jspb.Message.getFieldWithDefault(msg, 2, ""),
    destinationsList: jspb.Message.toObjectList(msg.getDestinationsList(),
    proto.adapter.Destination.toObject, includeInstance),
    extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.UpdateOptions}
 */
proto.adapter.UpdateOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.UpdateOptions;
  return proto.adapter.UpdateOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.UpdateOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.UpdateOptions}
 */
proto.adapter.UpdateOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage(value);
      break;
    case 3:
      var value = new proto.adapter.Destination;
      reader.readMessage(value,proto.adapter.Destination.deserializeBinaryFromReader);
      msg.addDestinations(value);
      break;
    case 4:
      var value = msg.getExtraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.UpdateOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.UpdateOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.UpdateOptions} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.UpdateOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getImage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDestinationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.adapter.Destination.serializeBinaryToWriter
    );
  }
  f = message.getExtraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
};


/**
 * optional string mode = 1;
 * @return {string}
 */
proto.adapter.UpdateOptions.prototype.getMode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.adapter.UpdateOptions.prototype.setMode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string image = 2;
 * @return {string}
 */
proto.adapter.UpdateOptions.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.adapter.UpdateOptions.prototype.setImage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated Destination destinations = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.adapter.Destination>}
 */
proto.adapter.UpdateOptions.prototype.getDestinationsList = function() {
  return /** @type{!Array.<!proto.adapter.Destination>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.adapter.Destination, 3));
};


/** @param {!Array.<!proto.adapter.Destination>} value */
proto.adapter.UpdateOptions.prototype.setDestinationsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.adapter.Destination=} opt_value
 * @param {number=} opt_index
 * @return {!proto.adapter.Destination}
 */
proto.adapter.UpdateOptions.prototype.addDestinations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.adapter.Destination, opt_index);
};


proto.adapter.UpdateOptions.prototype.clearDestinationsList = function() {
  this.setDestinationsList([]);
};


/**
 * map<string, google.protobuf.Value> extra = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.adapter.UpdateOptions.prototype.getExtraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


proto.adapter.UpdateOptions.prototype.clearExtraMap = function() {
  this.getExtraMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.Id = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adapter.Id, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.Id.displayName = 'proto.adapter.Id';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.Id.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.Id.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.Id} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.Id.toObject = function(includeInstance, msg) {
  var f, obj = {
    adapterApiKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    id: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.Id}
 */
proto.adapter.Id.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.Id;
  return proto.adapter.Id.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.Id} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.Id}
 */
proto.adapter.Id.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdapterApiKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.Id.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.Id.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.Id} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.Id.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAdapterApiKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string adapter_api_key = 1;
 * @return {string}
 */
proto.adapter.Id.prototype.getAdapterApiKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.adapter.Id.prototype.setAdapterApiKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.adapter.Id.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.adapter.Id.prototype.setId = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.Destination = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adapter.Destination, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.Destination.displayName = 'proto.adapter.Destination';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.Destination.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.Destination.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.Destination} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.Destination.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    extraMap: (f = msg.getExtraMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.Destination}
 */
proto.adapter.Destination.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.Destination;
  return proto.adapter.Destination.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.Destination} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.Destination}
 */
proto.adapter.Destination.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = msg.getExtraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.Destination.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.Destination.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.Destination} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.Destination.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExtraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.adapter.Destination.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.adapter.Destination.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * map<string, google.protobuf.Value> extra = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.adapter.Destination.prototype.getExtraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


proto.adapter.Destination.prototype.clearExtraMap = function() {
  this.getExtraMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.Progress = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.adapter.Progress, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.Progress.displayName = 'proto.adapter.Progress';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.Progress.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.Progress.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.Progress} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.Progress.toObject = function(includeInstance, msg) {
  var f, obj = {
    started: jspb.Message.getFieldWithDefault(msg, 1, 0),
    completed: jspb.Message.getFieldWithDefault(msg, 2, 0),
    duration: jspb.Message.getFieldWithDefault(msg, 3, 0),
    percentage: jspb.Message.getFieldWithDefault(msg, 4, 0),
    transferred: jspb.Message.getFieldWithDefault(msg, 5, 0),
    length: jspb.Message.getFieldWithDefault(msg, 6, 0),
    remaining: jspb.Message.getFieldWithDefault(msg, 7, 0),
    eta: jspb.Message.getFieldWithDefault(msg, 8, 0),
    runtime: jspb.Message.getFieldWithDefault(msg, 9, 0),
    speed: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.Progress}
 */
proto.adapter.Progress.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.Progress;
  return proto.adapter.Progress.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.Progress} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.Progress}
 */
proto.adapter.Progress.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStarted(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCompleted(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDuration(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPercentage(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTransferred(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLength(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemaining(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEta(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRuntime(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpeed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.Progress.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.Progress.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.Progress} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.Progress.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStarted();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCompleted();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getDuration();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getPercentage();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getTransferred();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getLength();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getRemaining();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getEta();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getRuntime();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getSpeed();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional int64 started = 1;
 * @return {number}
 */
proto.adapter.Progress.prototype.getStarted = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setStarted = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int64 completed = 2;
 * @return {number}
 */
proto.adapter.Progress.prototype.getCompleted = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setCompleted = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int64 duration = 3;
 * @return {number}
 */
proto.adapter.Progress.prototype.getDuration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setDuration = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int64 percentage = 4;
 * @return {number}
 */
proto.adapter.Progress.prototype.getPercentage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setPercentage = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional int64 transferred = 5;
 * @return {number}
 */
proto.adapter.Progress.prototype.getTransferred = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setTransferred = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional int64 length = 6;
 * @return {number}
 */
proto.adapter.Progress.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setLength = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional int64 remaining = 7;
 * @return {number}
 */
proto.adapter.Progress.prototype.getRemaining = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setRemaining = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional int64 eta = 8;
 * @return {number}
 */
proto.adapter.Progress.prototype.getEta = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setEta = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional int64 runtime = 9;
 * @return {number}
 */
proto.adapter.Progress.prototype.getRuntime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setRuntime = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional int64 speed = 10;
 * @return {number}
 */
proto.adapter.Progress.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.adapter.Progress.prototype.setSpeed = function(value) {
  jspb.Message.setField(this, 10, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.Job = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.adapter.Job.repeatedFields_, null);
};
goog.inherits(proto.adapter.Job, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.Job.displayName = 'proto.adapter.Job';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.adapter.Job.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.Job.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.Job.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.Job} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.Job.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0),
    destinationsList: jspb.Message.toObjectList(msg.getDestinationsList(),
    proto.adapter.Destination.toObject, includeInstance),
    progress: (f = msg.getProgress()) && proto.adapter.Progress.toObject(includeInstance, f),
    message: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.Job}
 */
proto.adapter.Job.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.Job;
  return proto.adapter.Job.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.Job} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.Job}
 */
proto.adapter.Job.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.adapter.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 3:
      var value = new proto.adapter.Destination;
      reader.readMessage(value,proto.adapter.Destination.deserializeBinaryFromReader);
      msg.addDestinations(value);
      break;
    case 4:
      var value = new proto.adapter.Progress;
      reader.readMessage(value,proto.adapter.Progress.deserializeBinaryFromReader);
      msg.setProgress(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.Job.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.Job.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.Job} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.Job.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDestinationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.adapter.Destination.serializeBinaryToWriter
    );
  }
  f = message.getProgress();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.adapter.Progress.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.adapter.Job.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.adapter.Job.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional State state = 2;
 * @return {!proto.adapter.State}
 */
proto.adapter.Job.prototype.getState = function() {
  return /** @type {!proto.adapter.State} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.adapter.State} value */
proto.adapter.Job.prototype.setState = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated Destination destinations = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.adapter.Destination>}
 */
proto.adapter.Job.prototype.getDestinationsList = function() {
  return /** @type{!Array.<!proto.adapter.Destination>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.adapter.Destination, 3));
};


/** @param {!Array.<!proto.adapter.Destination>} value */
proto.adapter.Job.prototype.setDestinationsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.adapter.Destination=} opt_value
 * @param {number=} opt_index
 * @return {!proto.adapter.Destination}
 */
proto.adapter.Job.prototype.addDestinations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.adapter.Destination, opt_index);
};


proto.adapter.Job.prototype.clearDestinationsList = function() {
  this.setDestinationsList([]);
};


/**
 * optional Progress progress = 4;
 * @return {?proto.adapter.Progress}
 */
proto.adapter.Job.prototype.getProgress = function() {
  return /** @type{?proto.adapter.Progress} */ (
    jspb.Message.getWrapperField(this, proto.adapter.Progress, 4));
};


/** @param {?proto.adapter.Progress|undefined} value */
proto.adapter.Job.prototype.setProgress = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.adapter.Job.prototype.clearProgress = function() {
  this.setProgress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.adapter.Job.prototype.hasProgress = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string message = 5;
 * @return {string}
 */
proto.adapter.Job.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.adapter.Job.prototype.setMessage = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.adapter.Jobs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.adapter.Jobs.repeatedFields_, null);
};
goog.inherits(proto.adapter.Jobs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.adapter.Jobs.displayName = 'proto.adapter.Jobs';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.adapter.Jobs.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.adapter.Jobs.prototype.toObject = function(opt_includeInstance) {
  return proto.adapter.Jobs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.adapter.Jobs} msg The msg instance to transform.
 * @return {!Object}
 */
proto.adapter.Jobs.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobsList: jspb.Message.toObjectList(msg.getJobsList(),
    proto.adapter.Job.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.adapter.Jobs}
 */
proto.adapter.Jobs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.adapter.Jobs;
  return proto.adapter.Jobs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.adapter.Jobs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.adapter.Jobs}
 */
proto.adapter.Jobs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.adapter.Job;
      reader.readMessage(value,proto.adapter.Job.deserializeBinaryFromReader);
      msg.addJobs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.adapter.Jobs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.adapter.Jobs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.adapter.Jobs} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.adapter.Jobs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.adapter.Job.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Job jobs = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.adapter.Job>}
 */
proto.adapter.Jobs.prototype.getJobsList = function() {
  return /** @type{!Array.<!proto.adapter.Job>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.adapter.Job, 1));
};


/** @param {!Array.<!proto.adapter.Job>} value */
proto.adapter.Jobs.prototype.setJobsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.adapter.Job=} opt_value
 * @param {number=} opt_index
 * @return {!proto.adapter.Job}
 */
proto.adapter.Jobs.prototype.addJobs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.adapter.Job, opt_index);
};


proto.adapter.Jobs.prototype.clearJobsList = function() {
  this.setJobsList([]);
};


/**
 * @enum {number}
 */
proto.adapter.State = {
  _: 0,
  STARTED: 1,
  COMPLETED: 2,
  FAILED: 3,
  TIMED_OUT: 4
};

goog.object.extend(exports, proto.adapter);
