// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adapter.proto

/*
Package adapter is a generated protocol buffer package.

It is generated from these files:
	adapter.proto

It has these top-level messages:
	ScanKey
	ScanOptions
	UpdateKey
	UpdateOptions
	Id
	Destination
	Progress
	Job
	Jobs
*/
package adapter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State__         State = 0
	State_STARTED   State = 1
	State_COMPLETED State = 2
	State_FAILED    State = 3
	State_TIMED_OUT State = 4
)

var State_name = map[int32]string{
	0: "_",
	1: "STARTED",
	2: "COMPLETED",
	3: "FAILED",
	4: "TIMED_OUT",
}
var State_value = map[string]int32{
	"_":         0,
	"STARTED":   1,
	"COMPLETED": 2,
	"FAILED":    3,
	"TIMED_OUT": 4,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ScanKey struct {
	AdapterApiKey string       `protobuf:"bytes,1,opt,name=adapter_api_key,json=adapterApiKey" json:"adapter_api_key,omitempty"`
	Options       *ScanOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
}

func (m *ScanKey) Reset()                    { *m = ScanKey{} }
func (m *ScanKey) String() string            { return proto.CompactTextString(m) }
func (*ScanKey) ProtoMessage()               {}
func (*ScanKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ScanKey) GetAdapterApiKey() string {
	if m != nil {
		return m.AdapterApiKey
	}
	return ""
}

func (m *ScanKey) GetOptions() *ScanOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type ScanOptions struct {
	Mode   string                             `protobuf:"bytes,1,opt,name=mode" json:"mode,omitempty"`
	Number int64                              `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	Delay  int64                              `protobuf:"varint,3,opt,name=delay" json:"delay,omitempty"`
	Extra  map[string]*google_protobuf1.Value `protobuf:"bytes,4,rep,name=extra" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ScanOptions) Reset()                    { *m = ScanOptions{} }
func (m *ScanOptions) String() string            { return proto.CompactTextString(m) }
func (*ScanOptions) ProtoMessage()               {}
func (*ScanOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ScanOptions) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *ScanOptions) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ScanOptions) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *ScanOptions) GetExtra() map[string]*google_protobuf1.Value {
	if m != nil {
		return m.Extra
	}
	return nil
}

type UpdateKey struct {
	AdapterApiKey string         `protobuf:"bytes,1,opt,name=adapter_api_key,json=adapterApiKey" json:"adapter_api_key,omitempty"`
	Options       *UpdateOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
}

func (m *UpdateKey) Reset()                    { *m = UpdateKey{} }
func (m *UpdateKey) String() string            { return proto.CompactTextString(m) }
func (*UpdateKey) ProtoMessage()               {}
func (*UpdateKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateKey) GetAdapterApiKey() string {
	if m != nil {
		return m.AdapterApiKey
	}
	return ""
}

func (m *UpdateKey) GetOptions() *UpdateOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type UpdateOptions struct {
	Mode         string                             `protobuf:"bytes,1,opt,name=mode" json:"mode,omitempty"`
	Image        string                             `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Destinations []*Destination                     `protobuf:"bytes,3,rep,name=destinations" json:"destinations,omitempty"`
	Extra        map[string]*google_protobuf1.Value `protobuf:"bytes,4,rep,name=extra" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *UpdateOptions) Reset()                    { *m = UpdateOptions{} }
func (m *UpdateOptions) String() string            { return proto.CompactTextString(m) }
func (*UpdateOptions) ProtoMessage()               {}
func (*UpdateOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateOptions) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *UpdateOptions) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UpdateOptions) GetDestinations() []*Destination {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *UpdateOptions) GetExtra() map[string]*google_protobuf1.Value {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Id struct {
	AdapterApiKey string `protobuf:"bytes,1,opt,name=adapter_api_key,json=adapterApiKey" json:"adapter_api_key,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Id) GetAdapterApiKey() string {
	if m != nil {
		return m.AdapterApiKey
	}
	return ""
}

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Destination struct {
	Id    string                             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Extra map[string]*google_protobuf1.Value `protobuf:"bytes,2,rep,name=extra" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Destination) Reset()                    { *m = Destination{} }
func (m *Destination) String() string            { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()               {}
func (*Destination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Destination) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Destination) GetExtra() map[string]*google_protobuf1.Value {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Progress struct {
	Started     int64 `protobuf:"varint,1,opt,name=started" json:"started,omitempty"`
	Completed   int64 `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
	Duration    int64 `protobuf:"varint,3,opt,name=duration" json:"duration,omitempty"`
	Percentage  int64 `protobuf:"varint,4,opt,name=percentage" json:"percentage,omitempty"`
	Transferred int64 `protobuf:"varint,5,opt,name=transferred" json:"transferred,omitempty"`
	Length      int64 `protobuf:"varint,6,opt,name=length" json:"length,omitempty"`
	Remaining   int64 `protobuf:"varint,7,opt,name=remaining" json:"remaining,omitempty"`
	Eta         int64 `protobuf:"varint,8,opt,name=eta" json:"eta,omitempty"`
	Runtime     int64 `protobuf:"varint,9,opt,name=runtime" json:"runtime,omitempty"`
	Speed       int64 `protobuf:"varint,10,opt,name=speed" json:"speed,omitempty"`
}

func (m *Progress) Reset()                    { *m = Progress{} }
func (m *Progress) String() string            { return proto.CompactTextString(m) }
func (*Progress) ProtoMessage()               {}
func (*Progress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Progress) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Progress) GetCompleted() int64 {
	if m != nil {
		return m.Completed
	}
	return 0
}

func (m *Progress) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Progress) GetPercentage() int64 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Progress) GetTransferred() int64 {
	if m != nil {
		return m.Transferred
	}
	return 0
}

func (m *Progress) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Progress) GetRemaining() int64 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *Progress) GetEta() int64 {
	if m != nil {
		return m.Eta
	}
	return 0
}

func (m *Progress) GetRuntime() int64 {
	if m != nil {
		return m.Runtime
	}
	return 0
}

func (m *Progress) GetSpeed() int64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Job struct {
	Id           string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	State        State          `protobuf:"varint,2,opt,name=state,enum=adapter.State" json:"state,omitempty"`
	Destinations []*Destination `protobuf:"bytes,3,rep,name=destinations" json:"destinations,omitempty"`
	Progress     *Progress      `protobuf:"bytes,4,opt,name=progress" json:"progress,omitempty"`
	Message      string         `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetState() State {
	if m != nil {
		return m.State
	}
	return State__
}

func (m *Job) GetDestinations() []*Destination {
	if m != nil {
		return m.Destinations
	}
	return nil
}

func (m *Job) GetProgress() *Progress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *Job) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Jobs struct {
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *Jobs) Reset()                    { *m = Jobs{} }
func (m *Jobs) String() string            { return proto.CompactTextString(m) }
func (*Jobs) ProtoMessage()               {}
func (*Jobs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Jobs) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanKey)(nil), "adapter.ScanKey")
	proto.RegisterType((*ScanOptions)(nil), "adapter.ScanOptions")
	proto.RegisterType((*UpdateKey)(nil), "adapter.UpdateKey")
	proto.RegisterType((*UpdateOptions)(nil), "adapter.UpdateOptions")
	proto.RegisterType((*Id)(nil), "adapter.Id")
	proto.RegisterType((*Destination)(nil), "adapter.Destination")
	proto.RegisterType((*Progress)(nil), "adapter.Progress")
	proto.RegisterType((*Job)(nil), "adapter.Job")
	proto.RegisterType((*Jobs)(nil), "adapter.Jobs")
	proto.RegisterEnum("adapter.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scan service

type ScanClient interface {
	StartScan(ctx context.Context, in *ScanKey, opts ...grpc.CallOption) (*Id, error)
	Status(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Jobs, error)
	Cancel(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Job, error)
}

type scanClient struct {
	cc *grpc.ClientConn
}

func NewScanClient(cc *grpc.ClientConn) ScanClient {
	return &scanClient{cc}
}

func (c *scanClient) StartScan(ctx context.Context, in *ScanKey, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/adapter.Scan/StartScan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) Status(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Jobs, error) {
	out := new(Jobs)
	err := grpc.Invoke(ctx, "/adapter.Scan/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) Cancel(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := grpc.Invoke(ctx, "/adapter.Scan/Cancel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scan service

type ScanServer interface {
	StartScan(context.Context, *ScanKey) (*Id, error)
	Status(context.Context, *Id) (*Jobs, error)
	Cancel(context.Context, *Id) (*Job, error)
}

func RegisterScanServer(s *grpc.Server, srv ScanServer) {
	s.RegisterService(&_Scan_serviceDesc, srv)
}

func _Scan_StartScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).StartScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Scan/StartScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).StartScan(ctx, req.(*ScanKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Scan/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Status(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Scan/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Cancel(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adapter.Scan",
	HandlerType: (*ScanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScan",
			Handler:    _Scan_StartScan_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Scan_Status_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Scan_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adapter.proto",
}

// Client API for Update service

type UpdateClient interface {
	StartUpdate(ctx context.Context, in *UpdateKey, opts ...grpc.CallOption) (*Id, error)
	Status(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Jobs, error)
	Cancel(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Job, error)
}

type updateClient struct {
	cc *grpc.ClientConn
}

func NewUpdateClient(cc *grpc.ClientConn) UpdateClient {
	return &updateClient{cc}
}

func (c *updateClient) StartUpdate(ctx context.Context, in *UpdateKey, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := grpc.Invoke(ctx, "/adapter.Update/StartUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) Status(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Jobs, error) {
	out := new(Jobs)
	err := grpc.Invoke(ctx, "/adapter.Update/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateClient) Cancel(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := grpc.Invoke(ctx, "/adapter.Update/Cancel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Update service

type UpdateServer interface {
	StartUpdate(context.Context, *UpdateKey) (*Id, error)
	Status(context.Context, *Id) (*Jobs, error)
	Cancel(context.Context, *Id) (*Job, error)
}

func RegisterUpdateServer(s *grpc.Server, srv UpdateServer) {
	s.RegisterService(&_Update_serviceDesc, srv)
}

func _Update_StartUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).StartUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Update/StartUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).StartUpdate(ctx, req.(*UpdateKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Update/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).Status(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Update_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adapter.Update/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServer).Cancel(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _Update_serviceDesc = grpc.ServiceDesc{
	ServiceName: "adapter.Update",
	HandlerType: (*UpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartUpdate",
			Handler:    _Update_StartUpdate_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Update_Status_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Update_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adapter.proto",
}

func init() { proto.RegisterFile("adapter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 810 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x76, 0x9c, 0x9f, 0xe3, 0x24, 0x84, 0x51, 0x14, 0x59, 0x51, 0x05, 0xc1, 0x42, 0x28,
	0xaa, 0x20, 0x41, 0x41, 0xa8, 0xa5, 0xe2, 0xa6, 0x34, 0x41, 0xa4, 0x3f, 0x6a, 0xe5, 0xa6, 0xdc,
	0x46, 0x93, 0x78, 0x1a, 0x0c, 0x89, 0x6d, 0xcd, 0x8c, 0x11, 0x11, 0xe2, 0x86, 0x57, 0xe0, 0x66,
	0x9f, 0x60, 0xdf, 0x62, 0xf7, 0x7e, 0xaf, 0xf7, 0x66, 0x1f, 0x60, 0x9f, 0x63, 0xb5, 0x9a, 0x19,
	0xff, 0xa5, 0xed, 0x45, 0x57, 0x2b, 0xf5, 0xce, 0xdf, 0xf9, 0xce, 0x39, 0x3e, 0xdf, 0x37, 0x73,
	0x06, 0x1a, 0xd8, 0xc3, 0x11, 0x27, 0x74, 0x10, 0xd1, 0x90, 0x87, 0xa8, 0x92, 0xc0, 0xee, 0xde,
	0x2a, 0x0c, 0x57, 0x6b, 0x32, 0xc4, 0x91, 0x3f, 0xc4, 0x41, 0x10, 0x72, 0xcc, 0xfd, 0x30, 0x60,
	0x2a, 0x2d, 0x63, 0x25, 0x5a, 0xc4, 0xb7, 0x43, 0xc6, 0x69, 0xbc, 0xe4, 0x8a, 0x75, 0x30, 0x54,
	0xae, 0x97, 0x38, 0x38, 0x23, 0x5b, 0xf4, 0x35, 0x7c, 0x9a, 0x74, 0x9c, 0xe3, 0xc8, 0x9f, 0xff,
	0x49, 0xb6, 0xb6, 0xd6, 0xd3, 0xfa, 0x35, 0x37, 0xfd, 0xef, 0x71, 0xe4, 0x8b, 0xbc, 0x01, 0x54,
	0xc2, 0x48, 0xfe, 0xc1, 0xd6, 0x7b, 0x5a, 0xdf, 0x1a, 0xb5, 0x07, 0xe9, 0x60, 0xa2, 0xd5, 0xa5,
	0xe2, 0xdc, 0x34, 0xc9, 0x79, 0xa3, 0x81, 0x55, 0x20, 0x10, 0x82, 0xd2, 0x26, 0xf4, 0x48, 0xd2,
	0x5c, 0x7e, 0xa3, 0x0e, 0x94, 0x83, 0x78, 0xb3, 0x20, 0x54, 0xb6, 0x34, 0xdc, 0x04, 0xa1, 0x36,
	0x98, 0x1e, 0x59, 0xe3, 0xad, 0x6d, 0xc8, 0xb0, 0x02, 0xe8, 0x07, 0x30, 0xc9, 0xdf, 0x9c, 0x62,
	0xbb, 0xd4, 0x33, 0xfa, 0xd6, 0xe8, 0x8b, 0x87, 0xfe, 0x3f, 0x98, 0x88, 0x8c, 0x49, 0xc0, 0xe9,
	0xd6, 0x55, 0xd9, 0xdd, 0x2b, 0x80, 0x3c, 0x88, 0x5a, 0x60, 0xe4, 0x12, 0xc5, 0x27, 0xfa, 0x06,
	0xcc, 0xbf, 0xf0, 0x3a, 0x26, 0x89, 0xac, 0xce, 0x40, 0x39, 0x37, 0x48, 0x9d, 0x1b, 0xfc, 0x26,
	0x58, 0x57, 0x25, 0x1d, 0xe9, 0x87, 0x9a, 0x43, 0xa0, 0x76, 0x13, 0x79, 0x98, 0x93, 0x0f, 0xf1,
	0xef, 0xbb, 0xbb, 0xfe, 0x75, 0xb2, 0xf9, 0x55, 0xb3, 0x7b, 0x0e, 0xbe, 0xd3, 0xa0, 0xb1, 0x43,
	0x3d, 0xe8, 0x61, 0x1b, 0x4c, 0x7f, 0x83, 0x57, 0x6a, 0xfc, 0x9a, 0xab, 0x00, 0x3a, 0x84, 0xba,
	0x47, 0x18, 0xf7, 0x03, 0x75, 0x29, 0x6c, 0x43, 0x5a, 0x96, 0x1f, 0xd9, 0x38, 0x27, 0xdd, 0x9d,
	0x4c, 0x74, 0xb0, 0xeb, 0xf2, 0x97, 0x0f, 0x4f, 0xf9, 0x24, 0x3e, 0xff, 0x04, 0xfa, 0xd4, 0x7b,
	0xb4, 0xc1, 0x4d, 0xd0, 0x7d, 0x2f, 0x71, 0x41, 0xf7, 0x3d, 0xe7, 0xb9, 0x06, 0x56, 0x41, 0x66,
	0xc2, 0x6b, 0x29, 0x9f, 0x5f, 0x27, 0xfd, 0xce, 0x75, 0x2a, 0x14, 0x3d, 0x89, 0xcc, 0x67, 0x3a,
	0x54, 0xaf, 0x68, 0xb8, 0xa2, 0x84, 0x31, 0x64, 0x43, 0x85, 0x71, 0x4c, 0x39, 0x51, 0xa3, 0x1a,
	0x6e, 0x0a, 0xd1, 0x1e, 0xd4, 0x96, 0xe1, 0x26, 0x5a, 0x13, 0xc1, 0xa9, 0x7d, 0xc9, 0x03, 0xa8,
	0x0b, 0x55, 0x2f, 0xa6, 0x72, 0xe8, 0x64, 0x6b, 0x32, 0x8c, 0x3e, 0x07, 0x88, 0x08, 0x5d, 0x92,
	0x80, 0x8b, 0x7b, 0x52, 0x92, 0x6c, 0x21, 0x82, 0x7a, 0x60, 0x71, 0x8a, 0x03, 0x76, 0x4b, 0x28,
	0x25, 0x9e, 0x6d, 0xca, 0x84, 0x62, 0x48, 0x2c, 0xea, 0x9a, 0x04, 0x2b, 0xfe, 0xbb, 0x5d, 0x56,
	0x8b, 0xaa, 0x90, 0x98, 0x89, 0x92, 0x0d, 0xf6, 0x03, 0x3f, 0x58, 0xd9, 0x15, 0x35, 0x53, 0x16,
	0x10, 0xe6, 0x10, 0x8e, 0xed, 0xaa, 0x8c, 0x8b, 0x4f, 0xa1, 0x8e, 0xc6, 0x01, 0xf7, 0x37, 0xc4,
	0xae, 0x29, 0x75, 0x09, 0x14, 0xd7, 0x98, 0x45, 0x84, 0x78, 0x36, 0xa8, 0x95, 0x97, 0xc0, 0x79,
	0xa9, 0x81, 0x71, 0x1a, 0x2e, 0xee, 0x9d, 0xdd, 0x57, 0x60, 0x32, 0x8e, 0xb9, 0x32, 0xb9, 0x39,
	0x6a, 0xe6, 0x4f, 0x81, 0x88, 0xba, 0x8a, 0xfc, 0x88, 0x25, 0xf8, 0x16, 0xaa, 0x51, 0x72, 0x22,
	0xd2, 0x2f, 0x6b, 0xf4, 0x59, 0x56, 0x95, 0x1e, 0x95, 0x9b, 0xa5, 0x08, 0x59, 0x1b, 0xc2, 0x98,
	0x70, 0xd7, 0x94, 0x33, 0xa6, 0xd0, 0xe9, 0x43, 0xe9, 0x34, 0x5c, 0x30, 0xd4, 0x83, 0xd2, 0x1f,
	0xe1, 0x82, 0xd9, 0x9a, 0x1c, 0xa1, 0x9e, 0x35, 0x3b, 0x0d, 0x17, 0xae, 0x64, 0xf6, 0x27, 0x60,
	0xca, 0xe1, 0x91, 0x09, 0xda, 0xbc, 0xf5, 0x09, 0xb2, 0xa0, 0x72, 0x3d, 0x3b, 0x76, 0x67, 0x93,
	0x71, 0x4b, 0x43, 0x0d, 0xa8, 0x9d, 0x5c, 0x5e, 0x5c, 0x9d, 0x4f, 0x04, 0xd4, 0x11, 0x40, 0xf9,
	0x97, 0xe3, 0xe9, 0xf9, 0x64, 0xdc, 0x32, 0x04, 0x35, 0x9b, 0x5e, 0x4c, 0xc6, 0xf3, 0xcb, 0x9b,
	0x59, 0xab, 0x34, 0x7a, 0xa1, 0x41, 0x49, 0xbc, 0x87, 0xe8, 0x67, 0xa8, 0x5d, 0x8b, 0x9b, 0x23,
	0x41, 0x6b, 0xe7, 0xad, 0x3c, 0x23, 0xdb, 0xae, 0x95, 0x45, 0xa6, 0x9e, 0xd3, 0xf9, 0xef, 0xf5,
	0xdb, 0xff, 0xf5, 0x96, 0x63, 0x0e, 0xd9, 0x12, 0x07, 0x47, 0xe9, 0x0b, 0x84, 0x0e, 0xa1, 0x2c,
	0x66, 0x8a, 0x19, 0x2a, 0xa6, 0x77, 0x1b, 0xc5, 0xf1, 0x99, 0x83, 0x64, 0x75, 0x1d, 0x81, 0xac,
	0x1e, 0xfe, 0xe3, 0x7b, 0xff, 0xa2, 0x03, 0x28, 0x9f, 0xe0, 0x60, 0x49, 0xd6, 0xbb, 0x95, 0x3b,
	0xc2, 0xd3, 0xc2, 0xfd, 0x42, 0xe1, 0xe8, 0x95, 0x06, 0x65, 0xf5, 0xd2, 0xa0, 0x5f, 0xc1, 0x92,
	0x0a, 0x12, 0x88, 0xee, 0xbc, 0x44, 0xf7, 0x54, 0xd8, 0xb2, 0x1d, 0x72, 0x2a, 0xc3, 0x58, 0x26,
	0xe4, 0x3a, 0x8e, 0x1e, 0xa5, 0xa3, 0x2d, 0xeb, 0x9b, 0xa8, 0x9e, 0xd4, 0x2b, 0x25, 0x3f, 0x3e,
	0x46, 0x49, 0x52, 0xba, 0xbf, 0x53, 0xba, 0x28, 0xcb, 0x9d, 0xff, 0xfe, 0x7d, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdf, 0x9d, 0xb0, 0x70, 0xc2, 0x07, 0x00, 0x00,
}
